version: '2.2'
services:
  django:
    volumes:
      - '.:/usr/src/sc'
      - '/home/user/test_data:/data'
    environment:
      DEBUG: 'True'
      GEONODE_LB_HOST_IP: 2c.puerti.co
      GEONODE_LB_PORT: 443
      SITEURL: https://2c.puerti.co/
      ALLOWED_HOSTS: "['2c.puerti.co']"
      GEOSERVER_PUBLIC_LOCATION: https://2c.puerti.co/geoserver/
      GEOSERVER_WEB_UI_LOCATION: https://2c.puerti.co/geoserver/
      HAYSTACK_SEARCH: 'True'
      SKIP_PERMS_FILTER: 'True'

  celery:
    environment:
      GEONODE_LB_HOST_IP: 2c.puerti.co
      GEONODE_LB_PORT: 443
      SITEURL: https://2c.puerti.co/
      ALLOWED_HOSTS: "['2c.puerti.co']"
      GEOSERVER_PUBLIC_LOCATION: https://2c.puerti.co/geoserver/
      GEOSERVER_WEB_UI_LOCATION: https://2c.puerti.co/geoserver/
      DEBUG: 'False'

  geoserver:
    environment:
      GEONODE_LB_HOST_IP: 2c.puerti.co
      GEONODE_LB_PORT: 443
      NGINX_BASE_URL: https://2c.puerti.co/

  geonode:
    environment:
      SERVER_NAME: 2c.puerti.co

volumes:
  geoserver-data-dir:
    external:
       name: ${COMPOSE_PROJECT_NAME}-gsdatadir
  dbdata:
    external:
       name: ${COMPOSE_PROJECT_NAME}-dbdata
       #  dbbackups:
       #    external:
       #     driver: ${BACKUPS_VOLUME_DRIVER}
       #    name: ${COMPOSE_PROJECT_NAME}-dbbackups
  statics:
    external:
      name: ${COMPOSE_PROJECT_NAME}-statics
